'use strict';
(()=>{
 const R=TuteRules,$=id=>document.getElementById(id),names={jugador1:'Tú',jugador2:'Rival 1',jugador3:'Compañero',jugador4:'Rival 2'};
 const assets={Oros:'oros.png',Copas:'copas.png',Espadas:'espadas.png',Bastos:'bastos.png'},figures={10:'sota.png',11:'caballo.png',12:'rey.jpg'},titles={1:'As',10:'Sota',11:'Caballo',12:'Rey'};
 const positions={1:[[50,50]],2:[[50,20],[50,80]],3:[[50,16],[50,50],[50,84]],4:[[25,20],[75,20],[25,80],[75,80]],5:[[25,20],[75,20],[50,50],[25,80],[75,80]],6:[[25,16],[75,16],[25,50],[75,50],[25,84],[75,84]],7:[[25,16],[75,16],[50,33],[25,50],[75,50],[25,84],[75,84]]};
 const read=(k,f)=>{try{return localStorage.getItem('tecnitute-'+k)??f;}catch{return f;}},save=(k,v)=>{try{localStorage.setItem('tecnitute-'+k,v);}catch{}};
 let tips=read('consejos','false')==='true',sound=read('sonido','true')==='true',volume=Math.max(0,Math.min(100,Number(read('volumen','50'))||0)),ctx;
 let game,selected=null,pending=false,epoch=0,timer,visualCalls={},endSound=false;
 const animations=new Set(),reduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 function audio(){if(!sound)return;try{ctx??=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume().catch(()=>{});}catch{}}
 document.addEventListener('pointerdown',audio,{passive:true});document.addEventListener('keydown',audio);
 function beep(kind){if(!sound||!ctx||ctx.state!=='running')return;const notes={card:[330,240],baza:[440,660],canto:[523,659,784],tute:[523,659,784,1047],win:[523,659,784,1047],lose:[392,330,262],deal:[220,294,330]}[kind]||[440];notes.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.105;o.type=kind==='card'?'triangle':'sine';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume/100*.09,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+.18);});}
 const label=c=>(titles[c.numero]||c.numero)+' de '+c.palo;
 function card(c,interactive=false,back=false){const el=document.createElement(interactive?'button':'div');el.className='card';if(back){el.classList.add('back');el.setAttribute('aria-hidden','true');return el;}el.classList.add('number-'+c.numero,'suit-'+c.palo.toLowerCase(),{Oros:'gold',Copas:'red',Espadas:'blue',Bastos:'green'}[c.palo]);el.dataset.card=R.key(c);el.setAttribute('aria-label',label(c));if(interactive)el.type='button';
  const img=`<img class="suit-image" src="assets/${assets[c.palo]}" alt="">`;
  el.innerHTML=`<span class="corner">${c.numero}</span><span class="corner bottom">${c.numero}</span>`;
  if(figures[c.numero]){el.classList.add('figure');el.innerHTML+=`<div class="figure-art"><img class="figure-image" src="assets/${figures[c.numero]}" alt=""></div><span class="figure-suit">${img}</span><span class="figure-caption">${label(c)}</span>`;}
  else el.innerHTML+=`<div class="pip-field">${positions[c.numero].map(([x,y])=>`<span class="pip" style="left:${x}%;top:${y}%">${img}</span>`).join('')}</div><span class="card-name">${c.palo}</span>`;
  return el;
 }
 function button(text,fn,css=''){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=css;b.disabled=pending;b.onclick=fn;$('actions').append(b);return b;}
 function schedule(fn,ms=1150){clearTimeout(timer);const e=epoch;timer=setTimeout(()=>{if(e===epoch)fn();},ms);}
 function settings(){document.body.classList.toggle('tips-on',tips);for(const [id,on,text]of[['btn-tips',tips,'Consejos'],['btn-sound',sound,'Sonido']]){$(id).textContent=text+' '+(on?'ON':'OFF');$(id).setAttribute('aria-pressed',String(on));}$('volume').value=volume;$('volume-value').textContent=volume+'%';}
 function render(){
  const ended=!!game.result,valid=new Set(game.legal('jugador1').map(R.key));
  for(const id of R.ids){const n=id.slice(-1),holder=$('cards-'+n);holder.replaceChildren();$(id).classList.toggle('active',game.actor===id);$('tag-'+n).textContent=game.mano===id?'MANO':'';$('call-'+n).textContent=visualCalls[id]||game.calls[id]||'';
   for(const c of game.hands[id]){const human=id==='jugador1',el=card(c,human,!human&&!ended);if(human){el.disabled=pending||!valid.has(R.key(c));el.classList.toggle('legal',valid.has(R.key(c)));el.classList.toggle('selected',selected===R.key(c));el.setAttribute('aria-pressed',String(selected===R.key(c)));el.onclick=()=>{selected=R.key(c);render();};}holder.append(el);}if(n!=='1')$('count-'+n).textContent=game.hands[id].length+' cartas';$('played-'+n).replaceChildren();
  }
  if(['playing','trick-complete'].includes(game.stage))for(const p of game.trick)$('played-'+p.id.slice(-1)).append(card(p.card));
  $('score-own').textContent=game.scores.nosotros;$('score-other').textContent=game.scores.ellos;$('games-own').textContent=game.match.nosotros+' / 3 manos';$('games-other').textContent=game.match.ellos+' / 3 manos';$('trump-name').textContent=game.trump;$('trump-image').src='assets/'+assets[game.trump];$('trump-image').alt=game.trump;
  $('hand-label').textContent='MANO: '+names[game.mano].toUpperCase();$('trick-label').textContent='BAZA '+game.trickNo+' / 10';$('trump-detail').textContent='Pinta '+label(game.trumpCard)+' · Reparte '+names[game.dealer]+'.';
  $('actions').replaceChildren();$('stage-label').textContent=ended?'RECUENTO':game.stage==='singing'?'LOS CANTES':'BAZA '+game.trickNo;
  $('message').textContent=ended?(game.result.side==='nosotros'?'¡La mano es vuestra!':'Esta se la llevan ellos'):pending?'La mesa está hablando…':game.actor==='jugador1'?(game.stage==='singing'?'¡Te toca cantar!':'Elige una carta'):game.actor?'Turno de '+names[game.actor]:'Recogiendo la baza…';
  $('help').textContent=game.stage==='singing'?'Tu pareja ganó la baza. Puedes cantar una vez con rey y caballo del mismo palo; primero las cuarenta.':'Las cartas iluminadas son legales. Asiste y monta; sin el palo, falla y pisa si puedes. Selecciona una carta y pulsa Jugar.';
  if(ended){button(game.stage==='match-over'?'Nueva partida':'Siguiente mano',()=>restart(game.stage==='match-over'),'primary');button('Ver recuento',()=>$('round-result').scrollIntoView({behavior:reduced()?'auto':'smooth',block:'center'}));}
  else if(!pending&&game.actor==='jugador1'&&game.stage==='singing'){if(game.canTute('jugador1'))button('¡TUTE!',()=>chant('jugador1','tute'),'dramatic');for(const suit of game.available('jugador1'))button((suit===game.trump?40:20)+' · '+suit,()=>chant('jugador1',suit),'primary');button('No cantar',()=>chant('jugador1',null));}
  else if(!pending&&game.actor==='jugador1'&&game.stage==='playing'){const c=game.hands.jugador1.find(c=>R.key(c)===selected);button(c?'Jugar '+label(c):'Selecciona tu carta',()=>play('jugador1',selected),'primary').disabled=!c||!valid.has(selected);}
  else {const b=button('Espera tu turno',()=>{});b.disabled=true;}
  $('round-result').hidden=!ended;
  if(ended){$('result-title').textContent=game.stage==='match-over'?(game.result.side==='nosotros'?'¡Campeones de la timba!':'Los rivales ganan la partida'):'Recuento de la mano';$('result-reason').textContent=game.result.reason.startsWith('tute')?'Victoria por '+game.result.reason.replaceAll('-',' ')+'. Puntuación parcial al cantar.':game.result.tie?'Empate: gana la pareja de la última baza.':'Cartas + cantes + diez de últimas.';$('score-detail').innerHTML=[['Cartas','cards'],['Cantes','chants'],['Diez de últimas','last']].map(([title,k])=>`<tr><td>${title}</td><td>${game.breakdown.nosotros[k]}</td><td>${game.breakdown.ellos[k]}</td></tr>`).join('')+`<tr class="total-row"><td>Total</td><td>${game.scores.nosotros}</td><td>${game.scores.ellos}</td></tr>`;}
  $('chant-list').textContent=game.chantLog.map(c=>names[c.id]+': '+c.amount+' en '+c.suit).join(' · ')||'Todavía no hay cantes.';
  $('history').replaceChildren();for(const h of game.history){const li=document.createElement('li');li.textContent='Baza '+h.number+' · '+names[h.winner]+': '+h.points+' puntos'+(h.number===10?' + 10 de últimas':'')+'. '+h.plays.map(p=>names[p.id]+': '+label(p.card)).join(' · ');$('history').append(li);}
 }
 async function fly(c,from,to){if(reduced()||!from||!to)return;const ghost=card(c),base=$('flights').getBoundingClientRect();ghost.classList.add('flight');Object.assign(ghost.style,{left:from.left-base.left+'px',top:from.top-base.top+'px',width:from.width+'px',height:from.height+'px'});$('flights').append(ghost);if(!ghost.animate){ghost.remove();return;}const a=ghost.animate([{transform:'translate(0,0) rotate(-8deg)',opacity:1},{transform:`translate(${to.left-from.left}px,${to.top-from.top}px) rotate(0deg) scale(${to.width/from.width},${to.height/from.height})`,opacity:1}],{duration:480,easing:'cubic-bezier(.2,.7,.3,1)',fill:'forwards'});animations.add(a);try{await a.finished;}catch{}finally{animations.delete(a);ghost.remove();}}
 async function play(id,key){if(pending)return;const c=game.hands[id].find(c=>R.key(c)===key);if(!c)return;const origin=id==='jugador1'?$('cards-1').querySelector(`[data-card="${key}"]`):$('cards-'+id.slice(-1)).lastElementChild;const from=origin?.getBoundingClientRect();if(!game.play(id,key))return;const e=epoch;pending=true;selected=null;visualCalls[id]=label(c);render();beep('card');const target=$('played-'+id.slice(-1)).firstElementChild,to=target.getBoundingClientRect();target.style.visibility='hidden';await fly(c,from,to);if(e!==epoch)return;target.style.visibility='';pending=false;render();schedule(drive,550);}
 async function collect(){if(pending||game.stage!=='trick-complete')return;pending=true;const e=epoch,win=R.winner(game.trick,game.trump),to=$(win.id).querySelector('.player-name').getBoundingClientRect();render();beep('baza');await Promise.all(game.trick.map(p=>{const el=$('played-'+p.id.slice(-1)).firstElementChild,from=el.getBoundingClientRect();el.style.visibility='hidden';return fly(p.card,from,to);}));if(e!==epoch)return;game.resolve();visualCalls[win.id]='¡BAZA PARA '+(R.sides[win.id]==='nosotros'?'NOSOTROS':'ELLOS')+'!';pending=false;render();schedule(drive,1000);}
 function chant(id,suit){if(pending)return;const amount=suit===game.trump?40:20;const ok=suit==='tute'?game.declareTute(id):suit?game.sing(id,suit):game.skip(id);if(!ok)return;visualCalls[id]=suit==='tute'?'¡TUTE!':suit?'¡'+amount+' EN '+suit.toUpperCase()+'!':'No canto';pending=true;render();if(suit){beep(suit==='tute'?'tute':'canto');$(id).classList.add('chanting');$('announcement').textContent=names[id]+' '+visualCalls[id];}schedule(()=>{$(id).classList.remove('chanting');pending=false;render();drive();},1400);}
 function drive(){if(pending)return;render();if(game.result){if(!endSound){endSound=true;beep(game.result.side==='nosotros'?'win':'lose');}return;}if(game.stage==='trick-complete'){schedule(collect,900);return;}if(game.actor==='jugador1')return;const id=game.actor;if(game.stage==='singing')schedule(()=>chant(id,game.canTute(id)?'tute':game.available(id)[0]||null),1300);else schedule(()=>play(id,R.key(R.pick(game.hands[id],game.trick,game.trump,id,game.used[id]))),1250);}
 function restart(fresh=true){epoch++;clearTimeout(timer);for(const a of animations)a.cancel();animations.clear();$('flights').replaceChildren();for(const id of R.ids)$(id).classList.remove('chanting');if(fresh||!game)game=new R.Game();else game.nextHand();pending=false;selected=null;visualCalls={};endSound=false;beep('deal');render();drive();}
 $('btn-tips').onclick=()=>{tips=!tips;save('consejos',String(tips));settings();};$('btn-sound').onclick=()=>{sound=!sound;save('sonido',String(sound));settings();if(sound){audio();beep('canto');}};$('volume').oninput=e=>{volume=Number(e.target.value);save('volumen',String(volume));settings();};$('btn-reset').onclick=()=>restart();
 settings();restart();
})();
